### ISSUE TITLE
i18n yaml structure

### ISSUE THREAD

**Issue by dvodvo** [DavyJonesLocker/client_side_validations#768]
the README only references once i18n data for error messages, specifically when creating a local validator

```
# config/locales/en.yml
en:
  errors:
    messages:
      email: "Not an email address"
```

However my expectation is that the YAML file should be:
```
en:
  activerecord:
    errors:
      messages:
        email: "Not an email address"
```

Which is it for CSV?  and if it is the former format, where does one find the master strings for `en` locale so that one may edit the file accordingly.

### System configuration*
5.2.3
**Ruby version**:
2.6.1

**Client Side Validations version**:
15.0.0
